### ISSUE TITLE
Var_DQN package missing

### ISSUE THREAD

**Issue by SliencerX** [umd-huang-lab/WocaR-RL#1]
Dear authors

Thanks for sharing this code! This is a great work! However, I can not run this code since that many part of the code relies on a package called "VaR_DQN" but I could not install it through "setup.py" nor find it in the repo.

I am looking forward to hearing from you!

**Comment by cheryyunl** [comment]
We have updated the package name. We are very sorry for the inconvenience due to our mistake.
